services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: malicke
      POSTGRES_PASSWORD: malicke
      POSTGRES_DB: malicke
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: